### PR TITLE
documentation improvements, code has been cleaned up too 🤷‍♂️ 

### PR DESCRIPTION
**Pull request by HedTB**

### CODE REVIEW

**Comment by Muggry** [comment]
nuts

**Comment by HedTB** [comment]
fr

**Comment by CMorrison82z** [comment]
Looks good for the most part, however the line "actorIndex %= actorCount + 1" does not work as you think it does.

**Comment by HedTB** [comment]
i think i messed that up, let me check on it

**Comment by HedTB** [comment]
found it, and fixed it, thanks for the letting me know

**Comment by CMorrison82z** [comment]
I think if you just correct the numbering order issue in the README, I'll merge

**Pull request merged**
